namespace EKIFVK.ChemicalLab.Services.Tracking {
    /// <summary>
    /// History type
    /// </summary>
    public enum Operation {
        AddNewUser = 0,
        DeleteUser = 1,
        ChangeUserDisplayName = 2,
        ResetUserPassword = 3,
        ChangeUserPassowrd = 4,
        ChangeUserGroup = 5,
        ChangeUserDisabled = 6,
        AddNewUserGroup = 100,
        DeleteUserGroup = 101,
        ChangeUserGroupName = 102,
        ChangeUserGroupNote = 103,
        ChangeUserGroupPermission = 104,
        ChangeUserGroupDisabled = 105,
        AddNewRoom = 200,
        AddNewPlace = 201,
        AddNewLocation = 202,
        DeleteRoom = 203,
        DeletePlace = 204,
        DeleteLocation = 205,
        ChangeRoomName = 206,
        ChangePlaceName = 207,
        ChangeLocationRoom = 208,
        ChangeLocationPlace = 209,
        AddNewUnit = 300,
        DeleteUnit = 301,
        ChangeUnitName = 302,
        AddNewPhysicalState = 400,
        DeletePhysicalState = 401,
        ChangePhysicalStateName = 402,
        AddNewDetailType = 500,
        DeleteDetailType = 501,
        ChangeDetailTypeName = 502,
        AddNewContainerType = 600,
        DeleteContainerType = 601,
        ChangeContainerTypeName = 602,
        AddNewItemDetail = 700,
        DeleteItemDetail = 701,
        ChangeItemDetailPrefix = 702,
        ChangeItemDetailName = 703,
        ChangeItemDetailUnit = 704,
        ChangeItemDetailContainerType = 705,
        ChangeItemDetailPhysicalState = 706,
        ChangeItemDetailMsds = 707,
        ChangeItemDetailMsdsDate = 708,
        ChangeItemDetailRequired = 709,
        ChangeItemDetailNote = 710,
        ChangeItemDetailDisabled = 711,
        UploadMsds = 800
    }
}